name: Deploy .NET Web APIs to Azure (Windows)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/AuthService/**'
      - 'backend/CatalogService/**'
      - 'backend/SearchService/**'

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        service: [AuthService, CatalogService, SearchService]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: |
          cd backend/${{ matrix.service }}
          dotnet restore

      - name: Build Application
        run: |
          cd backend/${{ matrix.service }}
          dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: |
          cd backend/${{ matrix.service }}
          dotnet publish --configuration Release --output ${{ runner.temp }}/publish-${{ matrix.service }}

      - name: Deploy to Azure App Service (Windows)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ matrix.service == 'AuthService' && 'auth-service-api' || matrix.service == 'CatalogService' && 'catalog-service-api' || 'search-service-api' }}
          publish-profile: ${{ matrix.service == 'AuthService' && secrets.AZURE_AUTH_SERVICE_PUBLISH_PROFILE || matrix.service == 'CatalogService' && secrets.AZURE_CATALOG_SERVICE_PUBLISH_PROFILE || secrets.AZURE_SEARCH_SERVICE_PUBLISH_PROFILE }}
          package: ${{ runner.temp }}/publish-${{ matrix.service }}
